# see  examples/simple-docker-compose.yml/.github/main.yml
name: Simple Docker Compose

on:
  pull_request:
  workflow_call:
    inputs: { }
    secrets: { }
env:
  COMPOSE_FILE: docker-compose.yml
  NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
jobs:
  simple-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup env
        run: cp .env.ci .env
      - name: Setup Docker Compose
        uses: yu-ichiro/spin-up-docker-compose-action@main
        with:
          file: ${{ env.COMPOSE_FILE }}
          cache-key: simple-docker-compose
#      - name: Check Batch Runner
#        run: docker compose -f ${{ env.COMPOSE_FILE }} up
      - name: Run establish a ngrok tunnel
        id: expose_ngrok
        uses: wikiteq/ngrok-tunneling-action@master
        with:
          timeout: 1h
          port: 80
          ngrok_authtoken: ${{ secrets.NGROK_TOKEN }}
          tunnel_type: http
      - name: Test action output
        run: echo ${{ steps.expose_ngrok.outputs.TUNNEL_URL }}
        shell: bash
      - name: Comment on PR
        if: ${{ steps.expose_ngrok.outputs.TUNNEL_URL != '' && github.event_name == 'pull_request' }}
        uses: mshick/add-pr-comment@v1
        id: comment
        with:
          message: "Ngrok tunnel is up at: ${{ steps.expose_ngrok.outputs.TUNNEL_URL }}. It will stay alive for 1 hour, re-trigger the workflow action to re-deploy."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update server variable
        run: echo "MW_SITE_SERVER=${{ steps.expose_ngrok.outputs.TUNNEL_URL }}" >> .env.ci
        shell: bash
      - name: Update server variable in settings
        run: echo "$wgServer='${{ steps.expose_ngrok.outputs.TUNNEL_URL }}';" >> _settings/LocalSettings.php
        shell: bash
      - name: Sleep
        run: sleep 3600s
        shell: bash
