# see  examples/simple-docker-compose.yml/.github/main.yml
name: Simple Docker Compose

on:
  pull_request:
  workflow_call:
    inputs: { }
    secrets: { }
env:
  COMPOSE_FILE: docker-compose.yml
  NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
jobs:
  simple-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Setup env
#        run: cp .env.ci .env
#      - name: Setup Docker Compose
#        uses: yu-ichiro/spin-up-docker-compose-action@main
#        with:
#          file: ${{ env.COMPOSE_FILE }}
#          cache-key: simple-docker-compose
#      - name: Check Batch Runner
#        run: docker compose -f ${{ env.COMPOSE_FILE }} up
      - name: Run establish a ngrok tunnel
        id: mediawiki_compose_test
        uses: apogiatzis/ngrok-tunneling-action@master
        with:
          timeout: 1h
          port: 4000
#          port: 80
          ngrok_authtoken: ${{ secrets.NGROK_TOKEN }}
          tunnel_type: http
