# see examples/simple-docker-compose.yml/.github/main.yml
name: Simple Docker Compose

on:
  pull_request:
  workflow_call:
    inputs: { }
    secrets: { }
env:
  COMPOSE_FILE: docker-compose.yml
jobs:
  simple-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Compose
        uses: yu-ichiro/spin-up-docker-compose-action@main
        with:
          file: ${{ env.COMPOSE_FILE }}
          cache-key: simple-docker-compose
      - name: Setup env
        run: cp .env.ci .env
      - name: Check Batch Runner
        run: docker compose -f ${{ env.COMPOSE_FILE }} up
