name: DeployerBot

on:
  pull_request:
#     types: [ labeled ]
  workflow_call:
    inputs: { }
    secrets: { }
env:
  COMPOSE_FILE: docker-compose.yml
concurrency: docker_compose_ngrok_free
jobs:
  simple-docker-compose:
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    steps:

      - name: "Check if user has write access"
        uses: "lannonbr/repo-permission-check-action@2.0.0"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        run: cp .env.ci .env

      - name: Update server variable
        run: echo "MW_SITE_SERVER=http://localhost" >> .env
        shell: bash

      - name: Setup Docker Compose
        uses: yu-ichiro/spin-up-docker-compose-action@main
        with:
          file: ${{ env.COMPOSE_FILE }}
          cache-key: simple-docker-compose

      - name: Give containers a moment to init
        run: sleep 30s
        shell: bash

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i
        working-directory: e2e
      - run: npm test
        working-directory: e2e
