name: DeployerBot

on:
  pull_request:
#    types: [ labeled ]
  workflow_call:
    inputs: {}
    secrets: {}
#concurrency: docker_compose_ngrok_free
jobs:
  deploy-tunnel:
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    permissions:
      deployments: write
      pull-requests: write
      actions: write
      statuses: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      -
      - name: Fetch check run ids
        id: fetch
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/actions/runs/{run_id}/jobs
          repo: ${{ github.repository }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo check run ids
        run: echo "job ids - ${{ toJSON(fromJSON(steps.fetch.outputs.data).jobs.*.id) }}

      - name: Confirm check
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          conclusion: 'neutral'
          name: 'deploy-tunnel'
          status: 'completed'

      - name: Deploy and tunnel
        uses: wikiteq/compose-deploy-tunnel-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          secret: ${{ secrets.BORE_TOKEN }}
          endpoint: stage-deploy.wikiteq.com
          port: 80
          file: docker-compose.yml
