name: DeployerBot

on:
  pull_request:
#    types: [ labeled ]
# test5
  workflow_call:
    inputs: {}
    secrets: {}
#concurrency: docker_compose_ngrok_free
jobs:
  deploy-tunnel:
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    permissions:
      deployments: write
      pull-requests: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and tunnel
        uses: wikiteq/compose-deploy-tunnel-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          secret: ${{ secrets.BORE_TOKEN }}
          endpoint: stage-deploy.wikiteq.com
          port: 80
          file: docker-compose.yml
